# Generated by Django 6.0.4 on 2026-04-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('responsavel', models.CharField(max_length=150)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estudante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudantes.estudante')),
            ],
        ),
    ]
