# Generated by Django 6.0.4 on 2026-04-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudantes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('estudante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudantes.estudante')),
                ('horario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.horarioatendimento')),
            ],
        ),
    ]
