# Generated by Django 6.0.4 on 2026-04-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nivel_permissao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissoes.nivelpermissao')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.grupousuario')),
                ('nivel_permissao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissoes.nivelpermissao')),
                ('permissao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissoes.permissao')),
            ],
        ),
    ]
