# Generated by Django 6.0.4 on 2026-04-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivelpermissao',
            old_name='descricao',
            new_name='nome',
        ),
    ]
