# Generated by Django 6.0.4 on 2026-04-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('data_em', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ComunicadoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunicado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunicados.comunicado')),
                ('grupo_usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.grupousuario')),
            ],
        ),
    ]
