# Generated by Django 6.0.4 on 2026-04-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComunicadoGrupo',
            new_name='GrupoComunicado',
        ),
    ]
