# Generated by Django 6.0.4 on 2026-04-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('senha_hash', models.CharField(max_length=255)),
                ('hora_criado', models.DateTimeField(auto_now_add=True)),
                ('mudou_senha', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=20)),
                ('data_bloqueio', models.DateTimeField(blank=True, null=True)),
                ('motivo_bloqueio', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo_usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.grupousuario')),
            ],
        ),
    ]
